name: GitHub Pages Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  spec-prod:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/spec-prod.yml
    with:
      pages: true
    secrets: inherit
